export PS1='\[\e[1;32m\]alumno@dev101x-lab\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]$(b=$(git branch --show-current 2>/dev/null); [ -n "$b" ] && printf " \e[33m(%s)\e[0m" "$b")\$ '
export TERM=xterm-256color
export LESS=-FRX
alias ls='ls --color=auto'
alias ll='ls -la --color=auto'
cd ~ 2>/dev/null
